---
title: "description"
output:
  html_document:
    keep_md: yes
params:
  tsv: "../../runs/HAdV-B55/bac.tsv"
  typ: "../../config/genotype.tsv"
  gff: "../../runs/HAdV-B55/gub.recombination_predictions.gff"
  ess: 200
---

```{r setup, include=FALSE}
suppressPackageStartupMessages({
  library(readr)
  library(dplyr)
  library(tidyr)
  library(stringr)
  library(ggplot2)
  library(BactDating)
})
knitr::opts_chunk$set(echo = F, warning = F, message = F)
options(width = 1000)
```

```{r load}
df <- (
  read_tsv(
    params$tsv,
    col_types = cols(
      dic = "d",
      rootprob = "d",
      rate = "d",
      ess.likelihood = "d",
      ess.prior = "d",
      ess.mu = "d",
      .default = "c"
    )
  ) %>%
    arrange(
      desc(ess.likelihood >= params$ess & ess.prior >= params$ess & ess.mu >= params$ess),
      dic
    )
)
run <- (
  slice_head(df, n = 1) %>%
    pull(path) %>% 
    file.path("../..", .) %>%
    qs::qread()
)
```

BactDating Model Comparison

```{r result}
select(df, mod, dic, rootprob, rate, ess.likelihood, ess.prior, ess.mu) %>%
  mutate(rate = round(rate, digits = 7)) %>%
  mutate(rootprob = round(rootprob, digits = 2)) %>%
  mutate(across(starts_with("ess."), round)) %>%
  rename(ess.like = ess.likelihood) %>%
  pander::pandoc.table(style = "grid")
```

Trace of BactDating Model (`r pull(slice_head(df, n = 1), mod)`)

```{r trace, fig.height=5, fig.width=10}
plot(run, "trace")
```

Divergence of Gubbins Maximum-Likelihood Tree

```{r rtt, fig.height=6, fig.width=10}
devnull <- with(
  run, 
  roottotip(
    initRoot(inputtree, inputtree$tip.date, useRec = T), 
    inputtree$tip.date, 
    showPredInt = "poisson"
  )
)
```

```{r reco, fig.height=10, fig.width=10}
df.gff <- ape::read.gff(params$gff)
if (nrow(df.gff) > 0) {
  df.typ <- read_tsv(params$typ, col_names = c("taxon", "genotype"), col_types = "ff")
  df.gff <- (
    select(df.gff, start, end, attributes) %>%
      apply(1, function(row) {
        attr <- str_split_fixed(Filter(nchar, str_split(row[["attributes"]], ";")[[1]]), "=", 2)
        attr[, 2] <- substr(attr[, 2], 2, nchar(attr[, 2]) - 1)
        attr <- setNames(attr[, 2], attr[, 1])
        taxon <- Filter(nchar, str_split(attr[["taxa"]], " ")[[1]])
        data.frame(
          taxon, t(row[c("start", "end")]), t(attr[setdiff(names(attr), "taxon")]),
          stringsAsFactors = F
        )
      }) %>%
      bind_rows() %>%
      mutate(
        across(all_of(c("start", "end", "snp_count")), as.integer),
        neg_log_likelihood = as.numeric(neg_log_likelihood),
        taxon = as.factor(taxon)
      )
  )
  df.gff <- (
    left_join(df.gff, mutate(filter(count(df.gff, start, end), n == 1)), by = c("start", "end")) %>% 
      replace_na(list(n = 0)) %>% 
      rename(internal = n) %>% 
      mutate(internal = !internal)
  )
  p1 <- (
    distinct(df.gff, start, end, neg_log_likelihood) %>%
      arrange(start) %>%
      ggplot() +
      geom_rect(aes(xmin = start, xmax = end, ymin = 0, ymax = neg_log_likelihood)) +
      labs(y = "-log(likelihood)") +
      theme_minimal() +
      theme(
        axis.text.x = element_blank(),
        text = element_text(family = "mono")
      )
  )
  p2 <- (
    left_join(df.gff, df.typ, by = "taxon") %>%
      ggplot() +
      geom_rect(
        aes(
          xmin = start,
          xmax = end,
          ymin = as.numeric(taxon) - 0.5,
          ymax = as.numeric(taxon) + 0.5,
          fill = genotype,
          alpha = snp_count
        ),
        color = "black"
      ) +
      scale_y_discrete(limits = levels(df.gff$taxon)) +
      labs(x = "position", y = "accession") +
      theme_minimal() +
      theme(
        legend.position = "bottom",
        text = element_text(family = "mono")
      )
  )
  p <- cowplot::plot_grid(p1, p2, ncol = 1, rel_heights = c(1, 4), align = "v")
  ggsave(paste(tools::file_path_sans_ext(params$gff), "pdf", sep = "."))
  p
} else {
  print("no recombination detected...")
}
```
