$schema: "http://json-schema.org/draft-06/schema#"

description: the parameters for the workflow

properties:

  # target: init
  repo:
    type: string
    description: the file path to the flat-file repo to create
  term:
    type: string
    description: the NCBI query
  email:
    type: string
    description: the e-mail to use to be polite to NCBI

  # output
  out:
    type: string
    description: the output file directory
    default: "results"
  
  name:
    type: string
    description: the name of the experiment
  accv:
    type: string
    description: the "accession.version" of the query

  # Gubbins
  itr:
    type: integer
    description: the maximum number of iterations
    default: 10
  gap:
    type: integer
    description: the value to filter out taxa with more than this percentage of gaps
    default: 25
  
  # BactDating
  model:
    type: array
    description: the models to use (poisson, negbin, strictgamma, relaxedgamma, mixedgamma, arc, carc, or mixedcarc)
    default:
      - poisson
      - negbin
      - strictgamma
      - relaxedgamma
      - mixedgamma
      - arc
      - carc
      - mixedcarc
  nbIts:
    type: integer
    description: the number of MCMC iterations to perform
    default: 10000
    # default: 1000000
  thin:
    type: integer
    description: the thining interval between recorded MCMC samples
    default: 100
  burn:
    type: number
    description: the burn-in
    default: 0.50

  # other
  auspice:
    type: string
    description: the path to the auspice config file
  seed:
    type: integer
    description: "the seed for the PRNG"
    default: 7080
  threads:
    type: integer
    description: the number of threads to use for parallel tasks
    default: 32
